@startuml 食品成分管理
left to right direction
' Actor '
actor User as user

' Usecase '
' CRUDのユースケースは「管理する」と表現する '
package 食品成分管理システム {
  usecase "食品成分を管理する" as UC1
  usecase "ユーザー情報を管理する" as UC2
}

' Association '
user --> UC1
user --> UC2
@enduml

/' memo
- システムで実現したいこと
  - 食品成分を登録したい
  - 食品成分を確認したい
  - 食品成分を変更したい
  - 食品成分を削除したい
  - ユーザー情報を登録/変更できるようにしたい
  - ユーザー情報を確認できるようにしたい

- ユースケースとアクターの候補を見つける
  - 誰が(アクターの候補)
    - ユーザー
  - 何をする(ユースケースの候補)
    - 食品成分を登録する
    - 食品成分を確認する
    - 食品成分を変更する
    - 食品成分を削除する
    - ログインする
    - ユーザー情報を登録/変更する
    - ユーザー情報を確認する
    - 登録ユーザー一覧を確認する

- システムで実現すべき範囲を明確にし、ユースケースとアクターの候補を見直す
  -  外部システムなどは使用しないので、候補に変更なし

- 候補を洗練し、ユースケースとアクターを明確にする
'/